# Generated by Django 4.2.24 on 2026-01-02 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_event_unique_together_event_capacity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-booked_at']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date']},
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('title', 'date', 'location')},
        ),
    ]
